# Generated by Django 5.2 on 2025-05-02 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionorder_quantity_productionconsumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
