# Generated by Django 5.2 on 2025-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesinvoicedetail_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
